name: steam-bluesky-notifier

env:
  STEAM_ID: ${{ secrets.STEAM_ID }}
  STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
  ATP_HOST: ${{ secrets.ATP_HOST }}
  ATP_IDENTIFIER: ${{ secrets.ATP_IDENTIFIER }}
  ATP_PASSWORD: ${{ secrets.ATP_PASSWORD }}

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run checker
        working-directory: ${{ github.workspace }}
        run: |
          npm install node-fetch
          node check.js
